name: UI to be tested, build and deployed

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Frontend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: Frontend/package-lock.json
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      working-directory: Frontend
      run: npm install
    
    - name: Run tests
      working-directory: Frontend
      run: npm run test

    - name: Build and deploy to GitHub Pages
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
